services:
  fastapi:
    build: ../
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./entrypoint.sh:/entrypoint.sh
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    networks:
      - app_network
    env_file:
      - ../.env
    entrypoint: /entrypoint.sh


networks:
    app_network:
        driver: bridge